ControlSystem/urls.py
# coding=utf-8

from __future__ import unicode_literals
from django.conf.urls import patterns, include, url
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib import admin
from usuarios.views import *
from serviciosWeb.views import *
from ingresos.views import ListaDeIngreso
from ingresos.views import ListaDeFotos

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ControlSystem.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #Pruebas
    url(r'^signup$', 'usuarios.views.signup', name='signup'),
    url(r'^multiply', multiply),

    #Administración
    url(r'^admin/', include(admin.site.urls)),

    #Usuarios
    url(r'^$', 'usuarios.views.main', name='main'),
    url(r'^login$', "usuarios.views.ingreso", name='login'),
    url(r'^logout$', 'usuarios.views.salir', name="logout"),
    url(r'^home$', 'usuarios.views.home', name='home'),
    url(r'^perfil$', 'usuarios.views.perfil', name='perfil'),
    url(r'^password', 'usuarios.views.password', name='password'),
    url(r'^change_done', 'usuarios.views.my_password_change_done', name='change_done'),
    url(r'^acercade$', 'usuarios.views.acercade', name='acercade'),


    #Búsquedas
    url(r'^buscar/1$', 'busquedas.views.cuenta', name='buscarCuenta'),
    url(r'^buscar/2$', 'busquedas.views.medidor', name='buscarMedidor'),
    url(r'^buscar/3$', 'busquedas.views.nombre', name='buscarNombre'),
    url(r'^buscar/4$', 'busquedas.views.geocodigo', name='buscarGeocodigo'),
    url(r'^busqueda$', 'busquedas.views.busqueda', name='busqueda'),

    #Fotos
    url(r'^listadefotos$', ListaDeFotos.as_view(), name='listadefotos'),
    url(r'^fotos/(?P<pk>\d+)/$', 'ingresos.views.fotos', name='fotos'),
    url(r'^borrarfoto/(?P<pk>\d+)/$', 'ingresos.views.borrarFoto', name='borrarfoto'),

    #Mapas
    url(r'^cuadrillas$', 'usuarios.views.cuadrillas', name='cuadrillas'),
    url(r'^mascuadrillas$', 'usuarios.views.masCuadrillas', name='mascuadrillas'),

    #Reportes
    url(r'^reportes$', 'usuarios.views.reportes', name='reportes'),
    url(r'^reportesmateriales$', 'usuarios.views.reporteMateriales', name='reportesmateriales'),
    url(r'^reportesactividades$', 'usuarios.views.reporteActividades', name='reportesactividades'),

    #Ingresos
    url(r'^ingresarsico$', 'ingresos.views.ingresarSico', name='ingresarSico'),
    url(r'^breferencia', 'ingresos.views.buscarReferencia', name='buscarReferencia'),
    url(r'^bcliente', 'ingresos.views.buscarCliente', name='buscarClienteIngreso'),
    url(r'^bmedidor', 'ingresos.views.buscarMedidor', name='buscarMedidorIngreso'),
    url(r'^guardaringreso', 'ingresos.views.guardarIngreso', name='guardarIngreso'),
    url(r'^ingreso/(?P<pk>\d+)/$', 'ingresos.views.ingreso', name='ingreso'),
    url(r'^eliminaringreso/(?P<pk>\d+)/$', 'ingresos.views.eliminarIngreso', name='eliminaringreso'),
    url(r'^listadeingresos$', ListaDeIngreso.as_view(), name='listadeingresos'),

    #Avance de Obra
    url(r'^avance$', 'ingresos.views.avance', name='avance'),

    #Estados de ingreso
    url(r'^continuaringreso/(?P<pk>\d+)/$', 'ingresos.views.continuar', name='continuaringreso'),

    #Servicios Web
    (r"^hello_world/", 'serviciosWeb.views.hello_world_service'),
    (r'^hello_world/service.wsdl', 'serviciosWeb.views.hello_world_service'),
    (r'^sw/usuarios', 'serviciosWeb.views.sw_usuarios'),
    (r'^sw/usuarios.wsdl', 'serviciosWeb.views.sw_usuarios'),
    (r'^sw/busquedas', 'serviciosWeb.views.sw_busquedas'),
    (r'^sw/busquedas.wsdl', 'serviciosWeb.views.sw_busquedas'),
    (r'^sw/ingresos', 'serviciosWeb.views.sw_ingresos'),
    (r'^sw/ingresos.wsdl', 'serviciosWeb.views.sw_ingresos'),

)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

busqueda/models.py
from django import forms
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm, forms


class TipoBusqueda(models.Model):

    TIPOSBUSQUEDA = (
        ('1', 'Cuenta'),
        ('2', 'Medidor'),
        ('3', 'Nombre'),
        ('4', 'Geocodigo'),
    )

    id = models.PositiveSmallIntegerField(primary_key=True)
    descripcion = models.CharField(max_length=1, choices=TIPOSBUSQUEDA)

    def __str__(self):
        return self.id


class VitacoraBusquedas(models.Model):

    TIPOSBUSQUEDA = (
        ('1', 'Cuenta'),
        ('2', 'Medidor'),
        ('3', 'Nombre'),
        ('4', 'Geocodigo'),
    )

    tipoBusq = models.CharField(max_length=1, choices=TIPOSBUSQUEDA, default='1', verbose_name='Buscar por ')
    fechaHora = models.DateTimeField(auto_now=True)
    consulta = models.CharField(max_length=17, null=False, verbose_name='')
    usuario = models.ForeignKey(User)
    estadoRetorno = models.BooleanField(default=False)

    def __str__(self):
        return 'Busqueda por :{0}, ({1})'.format(self.get_TipoBusq_display(), self.consulta)



#FORMULARIOS
class BusquedaForm(ModelForm):
    class Meta:
        model = VitacoraBusquedas
        fields = ['tipoBusq','consulta']

busquedas/models.py
# coding=utf-8
import user
from django import forms
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm
from ingresos.models import cliente
from inventario.models import medidor, marca


class vitacoraBusquedas(models.Model):
    TIPOSBUSQUEDA = (
        ('1', 'Cuenta'),
        ('2', 'Medidor'),
        ('3', 'Nombre'),
        ('4', 'Geocodigo'),
    )
    tipoBusq = models.CharField(max_length=1, choices=TIPOSBUSQUEDA, default='1', verbose_name='Buscar por ')
    fechaHora = models.DateTimeField(auto_now=True, auto_now_add=True, editable=True)
    consulta = models.CharField(max_length=20, null=False, verbose_name='')
    usuario = models.ForeignKey(User)
    estadoRetorno = models.BooleanField(default=True)

    def __str__(self):
        opciones = {
            '1': 'Cuenta',
            '2': 'Medidor',
            '3': 'Nombre',
            '4': 'Geocodigo'
        }
        return 'Busqueda por %s: %s, (%s)' % (opciones[self.tipoBusq], self.consulta, self.fechaHora)

    class Meta:
        verbose_name_plural="Búsquedas Realizadas"
        verbose_name="Registro de Búsqueda"


#FORMULARIOS
class BusquedaForm(ModelForm):
    usuario = forms.ModelChoiceField(queryset=User.objects.all(), widget=forms.HiddenInput())
    estadoRetorno = forms.BooleanField(widget=forms.HiddenInput())

    class Meta:
        model = vitacoraBusquedas
        fields = ['usuario', 'tipoBusq', 'consulta', 'estadoRetorno']

    def save(self, retorno=True, commit=True):
        vitacoraBusquedas = super(BusquedaForm, self).save(commit=False)
        vitacoraBusquedas.estadoRetorno = retorno
        if commit:
            vitacoraBusquedas.save()
        return vitacoraBusquedas

    def clean(self):
        cleaned_data = super(BusquedaForm, self).clean()
        tb = cleaned_data.get("tipoBusq")
        c = cleaned_data.get("consulta")

        if c and tb:
            # Only do something if both fields are valid so far.
            if tb == '1':
                if not c.isdigit() or len(c) > 8:
                    raise forms.ValidationError("Error, Cuenta ingresada no válida.")

            if tb == '2':
                if not c.isdigit() or len(c) >= 11:
                    raise forms.ValidationError("Error, Número de medidor ingresado no válido.")

            if tb == '3':
                if c.isdigit():
                    raise forms.ValidationError("Error, Nombre de ciente no valido.")

            if tb == '4':
                sp = c.split('.')
                if len(sp) != 5 \
                    or (not sp[0].isdigit()) \
                    or (not sp[1].isdigit()) \
                    or (not sp[2].isdigit()) \
                    or (not sp[3].isdigit()) \
                    or (not sp[4].isdigit()):

                    raise forms.ValidationError("Error, Geocódigo incorrecto.")

                elif len(sp[0]) > 2 or len(sp[0]) < 1 \
                    or len(sp[1]) > 2 or len(sp[1]) < 1 \
                    or len(sp[2]) > 2 or len(sp[2]) < 1 \
                    or len(sp[3]) > 3 or len(sp[3]) < 1 \
                    or len(sp[4]) > 7 or len(sp[4]) < 1:

                    raise forms.ValidationError("Error, Geocódigo no válido.")

                # Always return the full collection of cleaned data.
        return cleaned_data


class ClienteBuscado(ModelForm):
    geo = forms.CharField(label='Geocódigo', widget=forms.TextInput(attrs={'readonly': True}))
    provincia=forms.CharField(label='Provincia', widget=forms.TextInput(attrs={'readonly': True}))
    canton=forms.CharField(label='Cantón', widget=forms.TextInput(attrs={'readonly': True}))
    nparr=forms.CharField(label='nParroquia', widget=forms.HiddenInput(attrs={'readonly': True}))
    parroquia=forms.CharField(label='Parroquia', widget=forms.TextInput(attrs={'readonly': True}))
    direccion=forms.CharField(label='Dirección', widget=forms.TextInput(attrs={'readonly': True}))
    interseccion=forms.CharField(label='Intersección', widget=forms.TextInput(attrs={'readonly': True}))
    urbanizacion=forms.CharField(label='Urbanización', widget=forms.TextInput(attrs={'readonly': True}))

    class Meta:
        model = cliente

        fields = [
            'cuenta',
            'nombre',
            'ci_ruc',
            'geo',
            'provincia',
            'canton',
            'parroquia',
            'direccion',
            'interseccion',
            'urbanizacion',
            'estado',
            'deuda',
            'meses'
        ]

        widgets = {
            'cuenta': forms.TextInput(attrs={'readonly': True}),
            'nombre': forms.TextInput(attrs={'readonly': True}),
            'ci_ruc': forms.TextInput(attrs={'readonly': True}),
            'estado': forms.TextInput(attrs={'readonly': True}),
            'deuda': forms.TextInput(attrs={'readonly': True}),
            'meses': forms.TextInput(attrs={'readonly': True}),
        }

    def __init__(self, geo, ubicacion,  *args, **kwargs):
        super(ClienteBuscado, self).__init__(*args, **kwargs)
        self.fields['geo'].initial = str(geo)
        self.fields['provincia'].initial = str(geo.ruta.sector.canton.provincia.descripcion)
        self.fields['canton'].initial = str(geo.ruta.sector.canton.descripcion)
        self.fields['nparr'].initial = str(ubicacion.parroquia.num)
        self.fields['parroquia'].initial = str(ubicacion.parroquia.descripcion)
        self.fields['direccion'].initial = str(ubicacion.calle.descripcion1)
        self.fields['interseccion'].initial = str(ubicacion.interseccion.descripcion1)
        self.fields['urbanizacion'].initial = str(ubicacion.urbanizacion.descripcion)


class MedidorBuscado(ModelForm):
    marc = forms.CharField(label='Marca', widget=forms.TextInput(attrs={'readonly': True}))
    tecnologia = forms.CharField(label='Tecnología', widget=forms.TextInput(attrs={'readonly': True}))
    tension = forms.CharField(label='Tensión', widget=forms.TextInput(attrs={'readonly': True}))
    amperaje = forms.CharField(label='Amperaje', widget=forms.TextInput(attrs={'readonly': True}))
    fi = forms.CharField(label='Fecha/Inst.', widget=forms.TextInput(attrs={'readonly': True}))
    fd = forms.CharField(label='Fecha/Desinst.', widget=forms.TextInput(attrs={'readonly': True}))
    li = forms.CharField(label='Lectura/Inst.', widget=forms.TextInput(attrs={'readonly': True}))
    ld = forms.CharField(label='Lectura/Desinst.', widget=forms.TextInput(attrs={'readonly': True}))

    class Meta:
        model = medidor

        fields = [
            'fabrica',
            'serie',
            'lectura',
            'marc',
            'tipo',
            'tecnologia',
            'tension',
            'amperaje',
            'fases',
            'hilos',
            'digitos',
            'fi', 'li',
            'fd', 'ld'
        ]

        widgets = {
            'fabrica': forms.TextInput(attrs={'readonly': True}),
            'serie': forms.TextInput(attrs={'readonly': True}),
            'lectura': forms.TextInput(attrs={'readonly': True}),
            'marc': forms.TextInput(attrs={'readonly': True}),
            'tipo': forms.TextInput(attrs={'readonly': True}),
            'tecnologia': forms.TextInput(attrs={'readonly': True}),
            'tension': forms.TextInput(attrs={'readonly': True}),
            'amperaje': forms.TextInput(attrs={'readonly': True}),
            'fases': forms.TextInput(attrs={'readonly': True}),
            'hilos': forms.TextInput(attrs={'readonly': True}),
            'digitos': forms.TextInput(attrs={'readonly': True}),
            'fi': forms.TextInput(attrs={'readonly': True}),
            'li': forms.TextInput(attrs={'readonly': True}),
            'fd': forms.TextInput(attrs={'readonly': True}),
            'ld': forms.TextInput(attrs={'readonly': True}),
        }

    def __init__(self, marc, tecnologia, tension, amperaje, fi, fd, li, ld, *args, **kwargs):
        super(MedidorBuscado, self).__init__(*args, **kwargs)
        self.fields['marc'].initial = str(marc)+' '
        self.fields['tecnologia'].initial = str(tecnologia)
        self.fields['tension'].initial = str(tension)
        self.fields['amperaje'].initial = str(amperaje)
        self.fields['fi'].initial = str(fi)
        self.fields['fd'].initial = str(fd)
        self.fields['li'].initial = str(li)
        self.fields['ld'].initial = str(ld)

    def is_valid(self):
        valid = super(MedidorBuscado, self).is_valid()
        return True
    def clean(self):
        cleaned_data = super(MedidorBuscado, self).clean()
        print cleaned_data
        self.cleaned_data=cleaned_data
        return cleaned_data

busqueda/views.py
from dajax.core import Dajax
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, render_to_response

# Create your views here.
from django.template import RequestContext
from django_ajax.decorators import ajax
from busqueda.models import BusquedaForm, VitacoraBusquedas

@login_required()
def cuenta(request):
    return buscar(request, 1)

@login_required()
def medidor(request):
    return buscar(request, 2)

@login_required()
def nombre(request):
    return buscar(request, 3)

@login_required()
def geocodigo(request):
    return buscar(request, 4)

def buscar(request, tipo):

    form = BusquedaForm()

    data = {
        'form': form,
        'tipo': tipo,
        'nav': 'buscar'
    }
    return render_to_response('busqueda/buscar.html', data, context_instance=RequestContext(request))

@ajax()
def busqueda(request):
    dajax = Dajax()
    if request.method == 'POST':

        tipo = int(request.POST['tipo'])
        dato = str(request.POST['dato'])
        print tipo
        print dato
        u = int(request.POST['u'])


        Vitacora = VitacoraBusquedas(consulta=dato, tipoBusq=tipo)

        Vitacora.usuario = User.objects.get(id = u)
    #
    #     #Vitacora.estadoRetorno = BusquedaEnSico(tipoBusq, consulta)
    #
        Vitacora.save()

        form = BusquedaForm()
        data = {
            'formulario': form,
        }

        dajax.append('#listaResultados', 'innerHTML', render_to_response('busqueda/form.html', data))
        return dajax.calls

    else:

        print "NO es post"

busquedas/views.py
from dajax.core import Dajax
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
from django.template import RequestContext
from django_ajax.decorators import ajax
from busquedas.models import BusquedaForm
from ControlSystem.pComm.busquedas.scriptsBusquedas import buscar as b

# Create your views here.
@login_required()
def cuenta(request):
    return buscar(request, 1)


@login_required()
def medidor(request):
    return buscar(request, 2)


@login_required()
def nombre(request):
    return buscar(request, 3)


@login_required()
def geocodigo(request):
    return buscar(request, 4)


def buscar(request, tipo):
    form = BusquedaForm(initial={'usuario': request.user, 'estadoRetorno': True, })

    data = {
        'form': form,
        'tipo': tipo,
        'nav': 'buscar'
    }
    return render_to_response('busqueda/buscar.html', data, context_instance=RequestContext(request))


def comprobarFormBusqueda(form, sesionAct):
    dajax = Dajax()
    dajax.clear('#listaResultados', 'innerHTML')
    dajax.script("$('#cargando').hide();")
    if form.is_valid():
        tipo = str(form.cleaned_data["tipoBusq"])
        dato = str(form.cleaned_data["consulta"])
        #pythoncom.CoInitialize()
        buscando = b(sesionAct)
        dajax.script("$('#listaResultados').show();")
        dajax.script("$('#resultado').show();")
        dajax.append('#listaResultados', 'innerHTML', buscando.renderBusqueda(tipo, dato))
        dajax.script("$('#resultado').html($('#r').html());")
        dajax.script("$('#r').empty();")
        form.save()
    else:
        print form.errors

        try:
            dajax.append(
                '#err',
                'innerHTML',
                render_to_response('busqueda/error.html', {'errors': dict(form.errors)['__all__']})
            )
        except:
            dajax.append(
                '#err',
                'innerHTML',
                render_to_response('busqueda/error.html', {'errors': dict(form.errors)['consulta']})
            )
    return dajax.calls


@ajax()
def busqueda(request):
    if request.method == 'POST':
        print request.POST
        form = BusquedaForm(request.POST)
        return comprobarFormBusqueda(form, request.user.sesion_sico)
    else:
        cuenta(request)

ControlSystem/templates/busqueda/buscar.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load static %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block title %}
    {{ tipo }}
{% endblock %}

{% block jquery %}
    {{ block.super }}
    <script>

        //var dx=$('document');
        dx.ready(inicializarBuscar);

        function inicializarBuscar()
        {
            var y = $("#id_tipoBusq");
            y.find("option[value='1']").attr("selected",false);
            y.find("option[value="+ {{ tipo }} +"]").attr("selected",true);
            seleccion();
        }

        function seleccion()
        {
            var y = $("#id_tipoBusq");
            y.change
            (
                function ()
                {
                    var m = '';
                    $("#id_tipoBusq").find("option:selected").each
                    (
                        function()
                        {
                            m = $( this ).val()+'';
                        }
                    );

                    cambiar(m,$("#title"),$("#id_consulta"));
                }
            ).change();
        }

        function cambiar(m, x, z)
        {
            switch (m)
            {
                case '1':
                    x.html('Búsqueda por número de Cuenta');
                    z.attr('placeholder', 'Escriba un número de cuenta');
                    break;

                case '2':
                    x.html('Búsqueda por numero de Medidor');
                    z.attr('placeholder', 'Escriba un número de medidor');
                    break;

                case '3':
                    x.html('Búsqueda por Nombre de abonado');
                    z.attr('placeholder', 'Escriba apellidos del abonado');
                    break;

                case '4':
                    x.html('Búsqueda por Ruta de Lectura');
                    z.attr('placeholder', 'Escriba un geocodigo');
                    break;

                default:
                break;
            }
        }

        function buscarAjax(tipo, valorBuscado){
            $('#id_consulta').val(valorBuscado);
            $("#id_tipoBusq").val(tipo);
            envioRecepcionAjax
            (
                '{% url 'busqueda' %}',
                $('#b').serialize()
            );
            $('#cargando').show();
            $('#listaResultados').hide();
            $('#resultado').hide();
            return false;
        }

    </script>
{% endblock %}

{% block content %}
 
    {% if form.errors %}
        <p>{{ form.errors }}</p>
    {% endif %}
    <div class="container-fluid">
        <div class="row">
            <div class="vcenter col-md-4">
                <div class="panel panel-info">
                    <div class="panel-body">
                        <form role="form" class="form-group" id="b" name="b" method="post" action=""
                        onsubmit="return buscarAjax(($('#id_tipoBusq').val()), ($('#id_consulta').val()))"
                        >
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            <br><div id="err"></div>
                            {% buttons %}
                                <button type="submit" class="btn btn-primary">
                                    {% bootstrap_icon "search" %} Buscar
                                </button>
                            {% endbuttons %}

                        </form>
                    </div>
                </div>
            </div>
            <div id="cargando" class="text-center">
                <img src="{% static 'img/cargando.gif' %}" height="100px" width="100px" style="margin-top: 40px;">
            </div>
            <div id="listaResultados" class="col-md-8"></div>
        </div>

        <div class="row">
            <div id="resultado" class="col-md-12"></div>
        </div>
    </div>
 
{% endblock %}

{% block jqueryfooter %}
    <script>
        seleccion();
        $('#cargando').hide();
        //$('#err').hide();
    </script>
{% endblock %}

ControlSystem/templates/busqueda/error.html
<div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <label class="control-label" for="inputError">
        {% for e in errors %}
            {{ e }}
            <br>
        {% endfor %}
    </label>
</div>